/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxLoading {
        "backdropOpacity"?: number;
        "backdropTheme"?: "light" | "dark";
        "backdropVisible"?: boolean;
        "color"?: string;
        /**
          * If loading element should fill available space and center content both h and v.
         */
        "cover"?: boolean;
        "dismiss": () => Promise<void>;
        "header"?: string;
        "message"?: string;
        "progressBuffer"?: number;
        "progressMessage"?: string;
        "progressPercent"?: number;
        "progressType"?: "determinate" | "indeterminate";
        "progressValue"?: number;
        /**
          * The type of loader.
          * @inheritDoc
         */
        "type": "spinner" | "progress";
    }
}
declare global {
    interface HTMLIonxLoadingElement extends Components.IonxLoading, HTMLStencilElement {
    }
    var HTMLIonxLoadingElement: {
        prototype: HTMLIonxLoadingElement;
        new (): HTMLIonxLoadingElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-loading": HTMLIonxLoadingElement;
    }
}
declare namespace LocalJSX {
    interface IonxLoading {
        "backdropOpacity"?: number;
        "backdropTheme"?: "light" | "dark";
        "backdropVisible"?: boolean;
        "color"?: string;
        /**
          * If loading element should fill available space and center content both h and v.
         */
        "cover"?: boolean;
        "header"?: string;
        "message"?: string;
        "progressBuffer"?: number;
        "progressMessage"?: string;
        "progressPercent"?: number;
        "progressType"?: "determinate" | "indeterminate";
        "progressValue"?: number;
        /**
          * The type of loader.
          * @inheritDoc
         */
        "type"?: "spinner" | "progress";
    }
    interface IntrinsicElements {
        "ionx-loading": IonxLoading;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-loading": LocalJSX.IonxLoading & JSXBase.HTMLAttributes<HTMLIonxLoadingElement>;
        }
    }
}
