/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectProps } from "./SelectProps";
import { ValueComparator } from "./ValueComparator";
import { SelectItem } from "./SelectItem";
import { SelectLazyGroupItem } from "./SelectGroupItem";
import { FunctionalComponent } from "@stencil/core";
import { StyleEventDetail } from "@ionic/core";
import { SelectValueItem } from "./SelectValueItem";
import { SelectDividerItem } from "./SelectDividerItem";
export namespace Components {
    interface IonxSelect {
        /**
          * Whether value should be always returned as array, no matter if multiple is set to true.
          * @inheritDoc
         */
        "alwaysArray": boolean;
        /**
          * @inheritDoc
         */
        "checkValidator": SelectProps.CheckValidatorFn;
        /**
          * @inheritDoc
         */
        "comparator": ValueComparator;
        /**
          * @inheritDoc
         */
        "disabled": boolean;
        /**
          * @inheritDoc
         */
        "empty": boolean;
        /**
          * @inheritDoc
         */
        "items": SelectItem[];
        /**
          * @inheritDoc
         */
        "labelComponent"?: string | FunctionalComponent<SelectProps.LabelComponentProps>;
        /**
          * @inheritDoc
         */
        "labelFormatter"?: SelectProps.LabelFormatterFn;
        /**
          * @inheritDoc
         */
        "lazyItems": SelectProps.LazyItemsFn | SelectLazyGroupItem;
        /**
          * If multiple value selection is allowed.
          * @inheritDoc
         */
        "multiple": boolean;
        /**
          * @deprecated
         */
        "options": SelectItem[];
        /**
          * @inheritDoc
         */
        "overlay": SelectProps.Overlay;
        /**
          * @inheritDoc
         */
        "overlayOptions": SelectProps.OverlayOptions;
        /**
          * @inheritDoc
         */
        "overlayTitle": string;
        /**
          * @inheritDoc
         */
        "placeholder": string;
        "prefetch": boolean;
        /**
          * @inheritDoc
         */
        "readonly": boolean;
        /**
          * A function, that will be used for testing if value passes search critieria. Default implementation checks lowercased label of value against lowercased searched text.
          * @inheritDoc
         */
        "searchTest": SelectProps.SearchTestFn;
        /**
          * @inheritDoc
         */
        "separator"?: string;
        "setBlur": () => Promise<void>;
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * If multiple values selection can be sorted after selection.
          * @inheritDoc
         */
        "sortable": boolean;
        /**
          * @inheritDoc
         */
        "value": any;
    }
    interface IonxSelectOverlay {
        "checkValidator": (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator": ValueComparator;
        "empty": boolean;
        "items": SelectItem[];
        "labelFormatter"?: (value: any) => string;
        "lazyItems": () => Promise<Array<SelectValueItem | SelectDividerItem>>;
        "multiple": boolean;
        "overlay": "modal" | "popover";
        "overlayTitle": string;
        "searchTest": (query: string, value: any, label: string) => boolean;
        "sortable": boolean;
        "values": any[];
    }
    interface IonxTest {
    }
}
declare global {
    interface HTMLIonxSelectElement extends Components.IonxSelect, HTMLStencilElement {
    }
    var HTMLIonxSelectElement: {
        prototype: HTMLIonxSelectElement;
        new (): HTMLIonxSelectElement;
    };
    interface HTMLIonxSelectOverlayElement extends Components.IonxSelectOverlay, HTMLStencilElement {
    }
    var HTMLIonxSelectOverlayElement: {
        prototype: HTMLIonxSelectOverlayElement;
        new (): HTMLIonxSelectOverlayElement;
    };
    interface HTMLIonxTestElement extends Components.IonxTest, HTMLStencilElement {
    }
    var HTMLIonxTestElement: {
        prototype: HTMLIonxTestElement;
        new (): HTMLIonxTestElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-select": HTMLIonxSelectElement;
        "ionx-select-overlay": HTMLIonxSelectOverlayElement;
        "ionx-test": HTMLIonxTestElement;
    }
}
declare namespace LocalJSX {
    interface IonxSelect {
        /**
          * Whether value should be always returned as array, no matter if multiple is set to true.
          * @inheritDoc
         */
        "alwaysArray"?: boolean;
        /**
          * @inheritDoc
         */
        "checkValidator"?: SelectProps.CheckValidatorFn;
        /**
          * @inheritDoc
         */
        "comparator"?: ValueComparator;
        /**
          * @inheritDoc
         */
        "disabled"?: boolean;
        /**
          * @inheritDoc
         */
        "empty"?: boolean;
        /**
          * @inheritDoc
         */
        "items"?: SelectItem[];
        /**
          * @inheritDoc
         */
        "labelComponent"?: string | FunctionalComponent<SelectProps.LabelComponentProps>;
        /**
          * @inheritDoc
         */
        "labelFormatter"?: SelectProps.LabelFormatterFn;
        /**
          * @inheritDoc
         */
        "lazyItems"?: SelectProps.LazyItemsFn | SelectLazyGroupItem;
        /**
          * If multiple value selection is allowed.
          * @inheritDoc
         */
        "multiple"?: boolean;
        "onIonChange"?: (event: CustomEvent<{value: any}>) => void;
        "onIonFocus"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when the styles change.
         */
        "onIonStyle"?: (event: CustomEvent<StyleEventDetail>) => void;
        /**
          * @deprecated
         */
        "options"?: SelectItem[];
        /**
          * @inheritDoc
         */
        "overlay"?: SelectProps.Overlay;
        /**
          * @inheritDoc
         */
        "overlayOptions"?: SelectProps.OverlayOptions;
        /**
          * @inheritDoc
         */
        "overlayTitle"?: string;
        /**
          * @inheritDoc
         */
        "placeholder"?: string;
        "prefetch"?: boolean;
        /**
          * @inheritDoc
         */
        "readonly"?: boolean;
        /**
          * A function, that will be used for testing if value passes search critieria. Default implementation checks lowercased label of value against lowercased searched text.
          * @inheritDoc
         */
        "searchTest"?: SelectProps.SearchTestFn;
        /**
          * @inheritDoc
         */
        "separator"?: string;
        /**
          * If multiple values selection can be sorted after selection.
          * @inheritDoc
         */
        "sortable"?: boolean;
        /**
          * @inheritDoc
         */
        "value"?: any;
    }
    interface IonxSelectOverlay {
        "checkValidator"?: (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator"?: ValueComparator;
        "empty"?: boolean;
        "items"?: SelectItem[];
        "labelFormatter"?: (value: any) => string;
        "lazyItems"?: () => Promise<Array<SelectValueItem | SelectDividerItem>>;
        "multiple"?: boolean;
        "overlay": "modal" | "popover";
        "overlayTitle"?: string;
        "searchTest"?: (query: string, value: any, label: string) => boolean;
        "sortable"?: boolean;
        "values"?: any[];
    }
    interface IonxTest {
    }
    interface IntrinsicElements {
        "ionx-select": IonxSelect;
        "ionx-select-overlay": IonxSelectOverlay;
        "ionx-test": IonxTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-select": LocalJSX.IonxSelect & JSXBase.HTMLAttributes<HTMLIonxSelectElement>;
            "ionx-select-overlay": LocalJSX.IonxSelectOverlay & JSXBase.HTMLAttributes<HTMLIonxSelectOverlayElement>;
            "ionx-test": LocalJSX.IonxTest & JSXBase.HTMLAttributes<HTMLIonxTestElement>;
        }
    }
}
