/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ValueComparator } from "./ValueComparator";
import { SelectOption } from "./SelectOption";
import { FunctionalComponent } from "@stencil/core";
import { StyleEventDetail } from "@ionic/core";
export namespace Components {
    interface IonxSelect {
        /**
          * Whether value should be always returned as array, no matter if multiple is set to true.
         */
        "alwaysArray": boolean;
        "checkValidator": (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator": ValueComparator;
        "disabled": boolean;
        "empty": boolean;
        "labelComponent"?: string | FunctionalComponent<{value: any, option?: SelectOption, label: string, index: number, readonly?: boolean}>;
        "labelFormatter"?: (value: any) => string;
        "lazyOptions": () => Promise<SelectOption[]>;
        /**
          * If multiple value selection is allowed.
         */
        "multiple": boolean;
        "options": SelectOption[];
        /**
          * If multiple values selection can be ordered after selection.
         */
        "orderable": boolean;
        "overlay": "popover" | "modal";
        "overlayOptions": { whiteSpace?: "nowrap" | "normal", title?: string };
        "overlayTitle": string;
        "placeholder": string;
        "readonly": boolean;
        /**
          * A function, that will be used for testing if value passes search critieria. Default implementation checks lowercased label of value against lowercased searched text.
         */
        "searchTest": (query: string, value: any, label: string) => boolean;
        "separator"?: string;
        "setBlur": () => Promise<void>;
        "setFocus": (options?: FocusOptions) => Promise<void>;
        "value": any;
    }
    interface IonxSelectOrderable {
        "enabled": boolean;
        "values": any[];
    }
    interface IonxSelectOverlay {
        "checkValidator": (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator": ValueComparator;
        "empty": boolean;
        "labelFormatter"?: (value: any) => string;
        "multiple": boolean;
        "options": SelectOption[];
        "orderable": boolean;
        "overlay": "modal" | "popover";
        "overlayTitle": string;
        "searchTest": (query: string, value: any, label: string) => boolean;
        "values": any[];
    }
    interface IonxTest {
    }
}
declare global {
    interface HTMLIonxSelectElement extends Components.IonxSelect, HTMLStencilElement {
    }
    var HTMLIonxSelectElement: {
        prototype: HTMLIonxSelectElement;
        new (): HTMLIonxSelectElement;
    };
    interface HTMLIonxSelectOrderableElement extends Components.IonxSelectOrderable, HTMLStencilElement {
    }
    var HTMLIonxSelectOrderableElement: {
        prototype: HTMLIonxSelectOrderableElement;
        new (): HTMLIonxSelectOrderableElement;
    };
    interface HTMLIonxSelectOverlayElement extends Components.IonxSelectOverlay, HTMLStencilElement {
    }
    var HTMLIonxSelectOverlayElement: {
        prototype: HTMLIonxSelectOverlayElement;
        new (): HTMLIonxSelectOverlayElement;
    };
    interface HTMLIonxTestElement extends Components.IonxTest, HTMLStencilElement {
    }
    var HTMLIonxTestElement: {
        prototype: HTMLIonxTestElement;
        new (): HTMLIonxTestElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-select": HTMLIonxSelectElement;
        "ionx-select-orderable": HTMLIonxSelectOrderableElement;
        "ionx-select-overlay": HTMLIonxSelectOverlayElement;
        "ionx-test": HTMLIonxTestElement;
    }
}
declare namespace LocalJSX {
    interface IonxSelect {
        /**
          * Whether value should be always returned as array, no matter if multiple is set to true.
         */
        "alwaysArray"?: boolean;
        "checkValidator"?: (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator"?: ValueComparator;
        "disabled"?: boolean;
        "empty"?: boolean;
        "labelComponent"?: string | FunctionalComponent<{value: any, option?: SelectOption, label: string, index: number, readonly?: boolean}>;
        "labelFormatter"?: (value: any) => string;
        "lazyOptions"?: () => Promise<SelectOption[]>;
        /**
          * If multiple value selection is allowed.
         */
        "multiple"?: boolean;
        "onIonChange"?: (event: CustomEvent<{value: any}>) => void;
        "onIonFocus"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when the styles change.
         */
        "onIonStyle"?: (event: CustomEvent<StyleEventDetail>) => void;
        "options"?: SelectOption[];
        /**
          * If multiple values selection can be ordered after selection.
         */
        "orderable"?: boolean;
        "overlay"?: "popover" | "modal";
        "overlayOptions"?: { whiteSpace?: "nowrap" | "normal", title?: string };
        "overlayTitle"?: string;
        "placeholder"?: string;
        "readonly"?: boolean;
        /**
          * A function, that will be used for testing if value passes search critieria. Default implementation checks lowercased label of value against lowercased searched text.
         */
        "searchTest"?: (query: string, value: any, label: string) => boolean;
        "separator"?: string;
        "value"?: any;
    }
    interface IonxSelectOrderable {
        "enabled"?: boolean;
        "onOrderChanged"?: (event: CustomEvent<any[]>) => void;
        "values"?: any[];
    }
    interface IonxSelectOverlay {
        "checkValidator"?: (value: any, checked: boolean, otherCheckedValues: any[]) => any[];
        "comparator"?: ValueComparator;
        "empty"?: boolean;
        "labelFormatter"?: (value: any) => string;
        "multiple"?: boolean;
        "options"?: SelectOption[];
        "orderable"?: boolean;
        "overlay": "modal" | "popover";
        "overlayTitle"?: string;
        "searchTest"?: (query: string, value: any, label: string) => boolean;
        "values"?: any[];
    }
    interface IonxTest {
    }
    interface IntrinsicElements {
        "ionx-select": IonxSelect;
        "ionx-select-orderable": IonxSelectOrderable;
        "ionx-select-overlay": IonxSelectOverlay;
        "ionx-test": IonxTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-select": LocalJSX.IonxSelect & JSXBase.HTMLAttributes<HTMLIonxSelectElement>;
            "ionx-select-orderable": LocalJSX.IonxSelectOrderable & JSXBase.HTMLAttributes<HTMLIonxSelectOrderableElement>;
            "ionx-select-overlay": LocalJSX.IonxSelectOverlay & JSXBase.HTMLAttributes<HTMLIonxSelectOverlayElement>;
            "ionx-test": LocalJSX.IonxTest & JSXBase.HTMLAttributes<HTMLIonxTestElement>;
        }
    }
}
