/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TimeZoneDate } from "@co.mmons/js-utils/core";
import { StyleEventDetail } from "@ionic/core";
export namespace Components {
    interface IonxDateTimeInput {
        /**
          * @inheritDoc
         */
        "clearButtonIcon": string;
        /**
          * @inheritDoc
         */
        "clearButtonVisible": boolean;
        "clearValue": () => Promise<void>;
        /**
          * @inheritDoc
         */
        "dateOnly": boolean;
        /**
          * Timezone, that will be set, when new value is picked from picker. By default  time zone of current device will be used.
          * @inheritDoc
         */
        "defaultTimeZone": string | "current";
        /**
          * @inheritDoc
         */
        "disabled": boolean;
        /**
          * @inheritDoc
         */
        "formatOptions": Intl.DateTimeFormatOptions;
        "open": () => Promise<void>;
        /**
          * @inheritDoc
         */
        "placeholder": string;
        /**
          * @inheritDoc
         */
        "readonly": boolean;
        "setBlur": () => Promise<void>;
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * Whether timezone cannot be changed.
          * @inheritDoc
         */
        "timeZoneDisabled": boolean;
        /**
          * If time zone must be chosen, by default true.
          * @inheritDoc
         */
        "timeZoneRequired": boolean;
        /**
          * @inheritDoc
         */
        "value": TimeZoneDate;
    }
    interface IonxDateTimeInputOverlay {
        "dateOnly": boolean;
        "timeZoneDisabled": boolean;
        "timeZoneRequired": boolean;
        "value": TimeZoneDate;
    }
}
declare global {
    interface HTMLIonxDateTimeInputElement extends Components.IonxDateTimeInput, HTMLStencilElement {
    }
    var HTMLIonxDateTimeInputElement: {
        prototype: HTMLIonxDateTimeInputElement;
        new (): HTMLIonxDateTimeInputElement;
    };
    interface HTMLIonxDateTimeInputOverlayElement extends Components.IonxDateTimeInputOverlay, HTMLStencilElement {
    }
    var HTMLIonxDateTimeInputOverlayElement: {
        prototype: HTMLIonxDateTimeInputOverlayElement;
        new (): HTMLIonxDateTimeInputOverlayElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-date-time-input": HTMLIonxDateTimeInputElement;
        "ionx-date-time-input-overlay": HTMLIonxDateTimeInputOverlayElement;
    }
}
declare namespace LocalJSX {
    interface IonxDateTimeInput {
        /**
          * @inheritDoc
         */
        "clearButtonIcon"?: string;
        /**
          * @inheritDoc
         */
        "clearButtonVisible"?: boolean;
        /**
          * @inheritDoc
         */
        "dateOnly"?: boolean;
        /**
          * Timezone, that will be set, when new value is picked from picker. By default  time zone of current device will be used.
          * @inheritDoc
         */
        "defaultTimeZone"?: string | "current";
        /**
          * @inheritDoc
         */
        "disabled"?: boolean;
        /**
          * @inheritDoc
         */
        "formatOptions"?: Intl.DateTimeFormatOptions;
        "onIonChange"?: (event: CustomEvent<{value: TimeZoneDate}>) => void;
        "onIonFocus"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when the styles change.
         */
        "onIonStyle"?: (event: CustomEvent<StyleEventDetail>) => void;
        /**
          * @inheritDoc
         */
        "placeholder"?: string;
        /**
          * @inheritDoc
         */
        "readonly"?: boolean;
        /**
          * Whether timezone cannot be changed.
          * @inheritDoc
         */
        "timeZoneDisabled"?: boolean;
        /**
          * If time zone must be chosen, by default true.
          * @inheritDoc
         */
        "timeZoneRequired"?: boolean;
        /**
          * @inheritDoc
         */
        "value"?: TimeZoneDate;
    }
    interface IonxDateTimeInputOverlay {
        "dateOnly"?: boolean;
        "timeZoneDisabled"?: boolean;
        "timeZoneRequired"?: boolean;
        "value"?: TimeZoneDate;
    }
    interface IntrinsicElements {
        "ionx-date-time-input": IonxDateTimeInput;
        "ionx-date-time-input-overlay": IonxDateTimeInputOverlay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-date-time-input": LocalJSX.IonxDateTimeInput & JSXBase.HTMLAttributes<HTMLIonxDateTimeInputElement>;
            "ionx-date-time-input-overlay": LocalJSX.IonxDateTimeInputOverlay & JSXBase.HTMLAttributes<HTMLIonxDateTimeInputOverlayElement>;
        }
    }
}
