/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxVirtualScroller {
        "estimatedItemHeight": number;
        "itemKey"?: (item: any) => any;
        "items": any[];
        "preserveScrollPositionOnPrependItems": boolean;
        "renderItem": (item: any, index: number) => any;
    }
}
declare global {
    interface HTMLIonxVirtualScrollerElement extends Components.IonxVirtualScroller, HTMLStencilElement {
    }
    var HTMLIonxVirtualScrollerElement: {
        prototype: HTMLIonxVirtualScrollerElement;
        new (): HTMLIonxVirtualScrollerElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-virtual-scroller": HTMLIonxVirtualScrollerElement;
    }
}
declare namespace LocalJSX {
    interface IonxVirtualScroller {
        "estimatedItemHeight"?: number;
        "itemKey"?: (item: any) => any;
        "items": any[];
        "preserveScrollPositionOnPrependItems"?: boolean;
        "renderItem"?: (item: any, index: number) => any;
    }
    interface IntrinsicElements {
        "ionx-virtual-scroller": IonxVirtualScroller;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-virtual-scroller": LocalJSX.IonxVirtualScroller & JSXBase.HTMLAttributes<HTMLIonxVirtualScrollerElement>;
        }
    }
}
