/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BlockWidth } from "./BlockWidth";
import { BlockWidthsMap } from "./BlockWidthsMap";
export namespace Components {
    interface IonxBlock {
        "innerAlignment": "start" | "end" | "center";
        "innerStyle": {[key: string]: string};
        "innerWidth": BlockWidth | BlockWidthsMap;
        "margins": boolean;
        "padding": boolean;
    }
    interface IonxTest {
    }
}
declare global {
    interface HTMLIonxBlockElement extends Components.IonxBlock, HTMLStencilElement {
    }
    var HTMLIonxBlockElement: {
        prototype: HTMLIonxBlockElement;
        new (): HTMLIonxBlockElement;
    };
    interface HTMLIonxTestElement extends Components.IonxTest, HTMLStencilElement {
    }
    var HTMLIonxTestElement: {
        prototype: HTMLIonxTestElement;
        new (): HTMLIonxTestElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-block": HTMLIonxBlockElement;
        "ionx-test": HTMLIonxTestElement;
    }
}
declare namespace LocalJSX {
    interface IonxBlock {
        "innerAlignment"?: "start" | "end" | "center";
        "innerStyle"?: {[key: string]: string};
        "innerWidth"?: BlockWidth | BlockWidthsMap;
        "margins"?: boolean;
        "padding"?: boolean;
    }
    interface IonxTest {
    }
    interface IntrinsicElements {
        "ionx-block": IonxBlock;
        "ionx-test": IonxTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-block": LocalJSX.IonxBlock & JSXBase.HTMLAttributes<HTMLIonxBlockElement>;
            "ionx-test": LocalJSX.IonxTest & JSXBase.HTMLAttributes<HTMLIonxTestElement>;
        }
    }
}
