/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxTestRoot {
    }
}
declare global {
    interface HTMLIonxTestRootElement extends Components.IonxTestRoot, HTMLStencilElement {
    }
    var HTMLIonxTestRootElement: {
        prototype: HTMLIonxTestRootElement;
        new (): HTMLIonxTestRootElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-test-root": HTMLIonxTestRootElement;
    }
}
declare namespace LocalJSX {
    interface IonxTestRoot {
    }
    interface IntrinsicElements {
        "ionx-test-root": IonxTestRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-test-root": LocalJSX.IonxTestRoot & JSXBase.HTMLAttributes<HTMLIonxTestRootElement>;
        }
    }
}
