/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContextMenuItem } from "./ContextMenuItem";
export namespace Components {
    interface IonxContextMenu {
        "items": ContextMenuItem[];
    }
    interface IonxModuleTest {
    }
}
declare global {
    interface HTMLIonxContextMenuElement extends Components.IonxContextMenu, HTMLStencilElement {
    }
    var HTMLIonxContextMenuElement: {
        prototype: HTMLIonxContextMenuElement;
        new (): HTMLIonxContextMenuElement;
    };
    interface HTMLIonxModuleTestElement extends Components.IonxModuleTest, HTMLStencilElement {
    }
    var HTMLIonxModuleTestElement: {
        prototype: HTMLIonxModuleTestElement;
        new (): HTMLIonxModuleTestElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-context-menu": HTMLIonxContextMenuElement;
        "ionx-module-test": HTMLIonxModuleTestElement;
    }
}
declare namespace LocalJSX {
    interface IonxContextMenu {
        "items": ContextMenuItem[];
    }
    interface IonxModuleTest {
    }
    interface IntrinsicElements {
        "ionx-context-menu": IonxContextMenu;
        "ionx-module-test": IonxModuleTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-context-menu": LocalJSX.IonxContextMenu & JSXBase.HTMLAttributes<HTMLIonxContextMenuElement>;
            "ionx-module-test": LocalJSX.IonxModuleTest & JSXBase.HTMLAttributes<HTMLIonxModuleTestElement>;
        }
    }
}
