/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxGrid {
    }
    interface IonxGridCol {
        "sizeLg": string | number;
        "sizeMd": string | number;
        "sizeSm": string | number;
        "sizeXl": string | number;
        "sizeXs": string | number;
        "sizeXxl": string | number;
    }
    interface IonxGridRow {
    }
}
declare global {
    interface HTMLIonxGridElement extends Components.IonxGrid, HTMLStencilElement {
    }
    var HTMLIonxGridElement: {
        prototype: HTMLIonxGridElement;
        new (): HTMLIonxGridElement;
    };
    interface HTMLIonxGridColElement extends Components.IonxGridCol, HTMLStencilElement {
    }
    var HTMLIonxGridColElement: {
        prototype: HTMLIonxGridColElement;
        new (): HTMLIonxGridColElement;
    };
    interface HTMLIonxGridRowElement extends Components.IonxGridRow, HTMLStencilElement {
    }
    var HTMLIonxGridRowElement: {
        prototype: HTMLIonxGridRowElement;
        new (): HTMLIonxGridRowElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-grid": HTMLIonxGridElement;
        "ionx-grid-col": HTMLIonxGridColElement;
        "ionx-grid-row": HTMLIonxGridRowElement;
    }
}
declare namespace LocalJSX {
    interface IonxGrid {
    }
    interface IonxGridCol {
        "sizeLg"?: string | number;
        "sizeMd"?: string | number;
        "sizeSm"?: string | number;
        "sizeXl"?: string | number;
        "sizeXs"?: string | number;
        "sizeXxl"?: string | number;
    }
    interface IonxGridRow {
    }
    interface IntrinsicElements {
        "ionx-grid": IonxGrid;
        "ionx-grid-col": IonxGridCol;
        "ionx-grid-row": IonxGridRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-grid": LocalJSX.IonxGrid & JSXBase.HTMLAttributes<HTMLIonxGridElement>;
            "ionx-grid-col": LocalJSX.IonxGridCol & JSXBase.HTMLAttributes<HTMLIonxGridColElement>;
            "ionx-grid-row": LocalJSX.IonxGridRow & JSXBase.HTMLAttributes<HTMLIonxGridRowElement>;
        }
    }
}
