/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxLazyLoad {
        "container"?: "parent" | "self" | "content";
        "observeShadow"?: boolean;
    }
    interface IonxTest {
    }
    interface IonxTestShadow {
    }
}
declare global {
    interface HTMLIonxLazyLoadElement extends Components.IonxLazyLoad, HTMLStencilElement {
    }
    var HTMLIonxLazyLoadElement: {
        prototype: HTMLIonxLazyLoadElement;
        new (): HTMLIonxLazyLoadElement;
    };
    interface HTMLIonxTestElement extends Components.IonxTest, HTMLStencilElement {
    }
    var HTMLIonxTestElement: {
        prototype: HTMLIonxTestElement;
        new (): HTMLIonxTestElement;
    };
    interface HTMLIonxTestShadowElement extends Components.IonxTestShadow, HTMLStencilElement {
    }
    var HTMLIonxTestShadowElement: {
        prototype: HTMLIonxTestShadowElement;
        new (): HTMLIonxTestShadowElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-lazy-load": HTMLIonxLazyLoadElement;
        "ionx-test": HTMLIonxTestElement;
        "ionx-test-shadow": HTMLIonxTestShadowElement;
    }
}
declare namespace LocalJSX {
    interface IonxLazyLoad {
        "container"?: "parent" | "self" | "content";
        "observeShadow"?: boolean;
    }
    interface IonxTest {
    }
    interface IonxTestShadow {
    }
    interface IntrinsicElements {
        "ionx-lazy-load": IonxLazyLoad;
        "ionx-test": IonxTest;
        "ionx-test-shadow": IonxTestShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-lazy-load": LocalJSX.IonxLazyLoad & JSXBase.HTMLAttributes<HTMLIonxLazyLoadElement>;
            "ionx-test": LocalJSX.IonxTest & JSXBase.HTMLAttributes<HTMLIonxTestElement>;
            "ionx-test-shadow": LocalJSX.IonxTestShadow & JSXBase.HTMLAttributes<HTMLIonxTestShadowElement>;
        }
    }
}
