/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxHtmlEditor {
    }
}
declare global {
    interface HTMLIonxHtmlEditorElement extends Components.IonxHtmlEditor, HTMLStencilElement {
    }
    var HTMLIonxHtmlEditorElement: {
        prototype: HTMLIonxHtmlEditorElement;
        new (): HTMLIonxHtmlEditorElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-html-editor": HTMLIonxHtmlEditorElement;
    }
}
declare namespace LocalJSX {
    interface IonxHtmlEditor {
    }
    interface IntrinsicElements {
        "ionx-html-editor": IonxHtmlEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-html-editor": LocalJSX.IonxHtmlEditor & JSXBase.HTMLAttributes<HTMLIonxHtmlEditorElement>;
        }
    }
}
