/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonxLoading {
        "dismiss": () => Promise<void>;
        "fill": boolean;
        "header": string;
        "message": string;
        "progressBuffer": number;
        "progressMessage": string;
        "progressPercent": number;
        "progressType": "determinate" | "indeterminate";
        "progressValue": number;
        /**
          * The type of loader.
          * @inheritDoc
         */
        "type": "spinner" | "progress";
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIonxLoadingElement extends Components.IonxLoading, HTMLStencilElement {
    }
    var HTMLIonxLoadingElement: {
        prototype: HTMLIonxLoadingElement;
        new (): HTMLIonxLoadingElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-loading": HTMLIonxLoadingElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IonxLoading {
        "fill"?: boolean;
        "header"?: string;
        "message"?: string;
        "progressBuffer"?: number;
        "progressMessage"?: string;
        "progressPercent"?: number;
        "progressType"?: "determinate" | "indeterminate";
        "progressValue"?: number;
        /**
          * The type of loader.
          * @inheritDoc
         */
        "type"?: "spinner" | "progress";
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ionx-loading": IonxLoading;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-loading": LocalJSX.IonxLoading & JSXBase.HTMLAttributes<HTMLIonxLoadingElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
