/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ToolbarButtonType } from "./ToolbarButtonType";
import { ToolbarTitleWrap } from "./ToolbarTitleWrap";
export namespace Components {
    interface IonxToolbar {
        "button": ToolbarButtonType;
        "buttonHandler": () => void;
        "buttonIcon": string;
        "defaultBackHref": string;
        "titleVisible": boolean;
        "titleWrap": ToolbarTitleWrap;
    }
}
declare global {
    interface HTMLIonxToolbarElement extends Components.IonxToolbar, HTMLStencilElement {
    }
    var HTMLIonxToolbarElement: {
        prototype: HTMLIonxToolbarElement;
        new (): HTMLIonxToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-toolbar": HTMLIonxToolbarElement;
    }
}
declare namespace LocalJSX {
    interface IonxToolbar {
        "button": ToolbarButtonType;
        "buttonHandler"?: () => void;
        "buttonIcon"?: string;
        "defaultBackHref"?: string;
        "titleVisible"?: boolean;
        "titleWrap"?: ToolbarTitleWrap;
    }
    interface IntrinsicElements {
        "ionx-toolbar": IonxToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-toolbar": LocalJSX.IonxToolbar & JSXBase.HTMLAttributes<HTMLIonxToolbarElement>;
        }
    }
}
