/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextFieldTypes } from "@ionic/core";
export namespace Components {
    interface IonxTagsInput {
        "canBackspaceRemove": boolean;
        "canEnterAdd": boolean;
        "hideRemove": boolean;
        "maxTags": number;
        "placeholder": string;
        "readonly": boolean;
        "required"?: boolean;
        "separator": string;
        "sortFn": (a: string, b: string) => number;
        "sortable": boolean;
        "type": TextFieldTypes;
        "unique": boolean;
        "value": string[];
        "verifyFn": (tagSrt: string) => boolean;
    }
    interface IonxTest {
    }
}
declare global {
    interface HTMLIonxTagsInputElement extends Components.IonxTagsInput, HTMLStencilElement {
    }
    var HTMLIonxTagsInputElement: {
        prototype: HTMLIonxTagsInputElement;
        new (): HTMLIonxTagsInputElement;
    };
    interface HTMLIonxTestElement extends Components.IonxTest, HTMLStencilElement {
    }
    var HTMLIonxTestElement: {
        prototype: HTMLIonxTestElement;
        new (): HTMLIonxTestElement;
    };
    interface HTMLElementTagNameMap {
        "ionx-tags-input": HTMLIonxTagsInputElement;
        "ionx-test": HTMLIonxTestElement;
    }
}
declare namespace LocalJSX {
    interface IonxTagsInput {
        "canBackspaceRemove"?: boolean;
        "canEnterAdd"?: boolean;
        "hideRemove"?: boolean;
        "maxTags"?: number;
        "onIonChange"?: (event: CustomEvent<{value: string[]}>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "separator"?: string;
        "sortFn"?: (a: string, b: string) => number;
        "sortable"?: boolean;
        "type"?: TextFieldTypes;
        "unique"?: boolean;
        "value"?: string[];
        "verifyFn"?: (tagSrt: string) => boolean;
    }
    interface IonxTest {
    }
    interface IntrinsicElements {
        "ionx-tags-input": IonxTagsInput;
        "ionx-test": IonxTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionx-tags-input": LocalJSX.IonxTagsInput & JSXBase.HTMLAttributes<HTMLIonxTagsInputElement>;
            "ionx-test": LocalJSX.IonxTest & JSXBase.HTMLAttributes<HTMLIonxTestElement>;
        }
    }
}
